import { existsSync } from 'node:fs';
import { join } from 'node:path';

import { app, dialog, Menu, shell, type MenuItemConstructorOptions } from 'electron';

/**
 * Application menu carrying the third-party attribution documents.
 *
 * BuilderHelm is proprietary but ships permissively licensed components whose
 * terms require the copyright and licence text to travel with the binary.
 * Minified bundles cannot carry them, so the notices are shipped as documents
 * and reachable from the menu rather than buried in the application package.
 *
 * Every other submenu uses Electron's built-in roles, so the standard editing,
 * window, and application items keep working exactly as before.
 */

interface LegalDocument {
  readonly label: string;
  readonly file: string;
}

const legalDocuments: readonly LegalDocument[] = [
  { label: 'Third-Party Notices', file: 'THIRD_PARTY_NOTICES.txt' },
  { label: 'Chromium and Runtime Licences', file: 'LICENSES.chromium.html' },
  { label: 'Electron Licence', file: 'LICENSE.electron.txt' },
];

/**
 * Packaged builds place these beside the app bundle's resources. Unpackaged
 * development builds only have the generated notices, next to the main bundle.
 */
function resolveLegalDocument(file: string): string | null {
  const candidates = app.isPackaged
    ? [join(process.resourcesPath, file)]
    : [join(__dirname, '..', file), join(process.resourcesPath, file)];
  return candidates.find((candidate) => existsSync(candidate)) ?? null;
}

async function openLegalDocument(document: LegalDocument): Promise<void> {
  const path = resolveLegalDocument(document.file);
  if (path === null) {
    await dialog.showMessageBox({
      type: 'info',
      message: `${document.label} is not present in this build`,
      detail:
        'Attribution documents are generated by the production build. Run pnpm build, or use a packaged application.',
      buttons: ['OK'],
      defaultId: 0,
      noLink: true,
    });
    return;
  }
  // Returns a non-empty string on failure rather than throwing.
  const failure = await shell.openPath(path);
  if (failure.length > 0) {
    await dialog.showMessageBox({
      type: 'error',
      message: `Could not open ${document.label}`,
      detail: failure,
      buttons: ['OK'],
      defaultId: 0,
      noLink: true,
    });
  }
}
/**
 * Chromium zoom on the shell breaks the embedded preview: the page is a
 * child WebContentsView whose bounds are CSS pixels from the renderer, and
 * those stop matching window coordinates once the shell zooms. Zoom In/Out
 * therefore change the preview page, not the chrome.
 */
let previewZoom: { in: () => void; out: () => void; reset: () => void } | null = null;

export function setPreviewZoomHandlers(next: {
  in: () => void;
  out: () => void;
  reset: () => void;
}): void {
  previewZoom = next;
}

export function installApplicationMenu(): void {
  const template: MenuItemConstructorOptions[] = [
    ...(process.platform === 'darwin'
      ? ([{ role: 'appMenu' }] satisfies MenuItemConstructorOptions[])
      : []),
    { role: 'fileMenu' },
    { role: 'editMenu' },
    {
      label: 'View',
      submenu: [
        { role: 'reload' },
        { role: 'forceReload' },
        { role: 'toggleDevTools' },
        { type: 'separator' },
        {
          label: 'Actual Size',
          accelerator: 'CommandOrControl+0',
          click: () => previewZoom?.reset(),
        },
        {
          label: 'Zoom In',
          accelerator: 'CommandOrControl+Plus',
          click: () => previewZoom?.in(),
        },
        {
          label: 'Zoom In',
          accelerator: 'CommandOrControl+=',
          visible: false,
          acceleratorWorksWhenHidden: true,
          click: () => previewZoom?.in(),
        },
        {
          label: 'Zoom Out',
          accelerator: 'CommandOrControl+-',
          click: () => previewZoom?.out(),
        },
        { type: 'separator' },
        { role: 'togglefullscreen' },
      ],
    },
    { role: 'windowMenu' },
    {
      role: 'help',
      submenu: legalDocuments.map((document) => ({
        label: document.label,
        click: () => {
          void openLegalDocument(document);
        },
      })),
    },
  ];
  Menu.setApplicationMenu(Menu.buildFromTemplate(template));
}
